### ISSUE TITLE
🐛 Bug: content_scripts is injected only when page is refreshed

### ISSUE THREAD

**Issue by estevezluis** [JoshuaKGoldberg/refined-saved-replies#155]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.

### Expected

When the URL is NOT `https://github.com/*/*/issues/` then changes to `https://github.com/*/*/issues/*`, I expect content_scripts to be injected.

### Actual

When navigating through github links, and eventually landing on the `https://github.com/*/*/issues/*` pattern, content_scripts is NOT injected.

content_scripts only runs when `https://github.com/*/*/issues/*` page is refreshed.

### Additional Info

This behavior is consistent in firefox (using main branch) and chrome (using extension from chrome web store) 

NOTE: Need to test other situations like navigating from other domains to git

**Comment by JoshuaKGoldberg** [comment]
Between #154's title and this issue's body, we have a full bug report! 😄 

And it's an interesting one. Thanks for filing! I'm confidently guessing it's because GitHub overrides page navigation to only partially update the page, for performance. Fun benefit of modern web architectures is that the page doesn't go through a whole traditional lifecycle between URL changes.

We'll have to re-run some logic every time the URL changes from a not-issue/PR to an issue/PR.
